name = "HomalgProject"
uuid = "50bd374c-87b5-11e9-015a-2febe71398bd"
authors = ["Mohamed Barakat <mohamed.barakat@uni-siegen.de>"]
version = "1.2.3"

[deps]
CapAndHomalg = "c4774649-1891-41ea-a883-87141804c57c"
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Singular = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"

[compat]
CapAndHomalg = "1.4.5"
GAP = "0.7, 0.8"
Singular = "0.8, 0.9, 0.10, 0.11, 0.12"
julia = "1.6, 1.7"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Documenter"]
