name = "HomalgProject"
uuid = "50bd374c-87b5-11e9-015a-2febe71398bd"
authors = ["Mohamed Barakat <mohamed.barakat@uni-siegen.de>"]
version = "0.1.3"

[deps]
GAP = "c863536a-3901-11e9-33e7-d5cd0df7b904"
Singular = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"

[compat]
julia = "1.1, 1.2, 1.3"
GAP = "^0.2.6"
Singular = "^0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
